# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [7]:
cityweather_df = pd.read_csv("../WeatherPY/Output/cities.csv", index_col=0)
cityweather_df = cityweather_df.dropna()
cityweather_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,huilong,0,CN,1598218988,92,31.81,121.66,82.99,1.99
1,bluff,35,NZ,1598218988,94,-46.60,168.33,46.99,12.64
2,ushuaia,20,AR,1598218989,74,-54.80,-68.30,35.60,9.17
3,pangody,89,RU,1598218989,91,65.85,74.49,53.20,6.80
4,palauig,77,PH,1598218989,78,15.44,119.90,81.21,6.53
...,...,...,...,...,...,...,...,...,...
562,hue,40,VN,1598219080,83,16.47,107.60,80.60,2.24
563,at-bashi,0,KG,1598219126,40,41.17,75.81,54.45,2.08
564,shahrud,2,IR,1598218857,66,36.42,54.98,63.63,14.09
565,novikovo,57,RU,1598219127,66,51.15,37.89,60.84,2.62
566,druzhba,25,UA,1598219127,64,52.04,33.95,59.20,8.90

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [8]:
gmaps.configure(api_key=g_key)
locations = cityweather_df[["Lat", "Lng"]]
humidity = cityweather_df["Humidity"]

In [15]:
fig = gmaps.figure(zoom_level = 1.5, center = (0,0))
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 3,  )
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [18]:
narrowed_df = cityweather_df.loc[(cityweather_df["Max Temp"] < 80) & (cityweather_df["Max Temp"] > 70) & 
                                 (cityweather_df["Wind Speed"] < 10) & (cityweather_df["Cloudiness"] == 0)]
narrowed_df = narrowed_df.reset_index(drop=True)
narrowed_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,biak,0,ID,1598219022,69,-0.91,122.88,74.25,3.33
1,komsomolskiy,0,UZ,1598219031,40,40.43,71.72,73.40,6.93
2,arona,0,ES,1598219047,78,28.10,-16.68,78.01,3.36
3,ayios serafim,0,GR,1598219057,60,38.80,22.70,75.99,1.99
4,surt,0,LY,1598219060,81,31.21,16.59,78.91,7.36
5,garmsar,0,IR,1598219067,49,35.22,52.34,71.46,6.85
6,mahon,0,ES,1598219098,73,39.89,4.27,73.40,4.70
7,campo de criptana,0,ES,1598219099,70,39.40,-3.12,73.00,5.01
8,jiaojiang,0,CN,1598219108,95,28.68,121.44,78.01,3.31
9,antibes,0,FR,1598219112,73,43.56,7.13,77.00,3.36
10,ganzhou,0,CN,1598218974,81,28.82,115.43,79.21,2.08

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [21]:
hotel_df = []

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure